server:
  port: 8081

spring:
  application:
    name : organization-service
  profiles:
    active : dev
  config:
    import: "optional:configserver:"

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka : true
    fetchRegistry : true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/